FROM python:3.12
# WORKDIR /usr/local/app/random_other_folder
# WORKDIR /home/arthur
WORKDIR /usr/local
# RUN useradd arthur
# USER arthur
RUN git clone https://github.com/Gwizdo51/personal_dump.git
WORKDIR /usr/local/personal_dump
# CMD python
CMD ["bash"]
