name: "filebrowser"

networks:
  filebrowser_net:
    external: false

services:

  filebrowser_container:
    container_name: "filebrowser_container"
    networks:
    - "filebrowser_net"
    image: "filebrowser/filebrowser"
    volumes:
    - "<path/to/folder>:/srv"
    - "/srv/docker_data/filebrowser/filebrowser.db:/database.db"
    user: "1000:1000"
    ports:
    - "80:80"
    restart: "unless-stopped"
