name: "wakeonlan_server"

services:

  wakeonlan_server_container:
    container_name: "wakeonlan_server_container"
    # spawn from a Dockerfile
    build:
      context: "./"
      target: "wakeonlan_server_img"
    # wakeonlan needs the "host" network mode to work
    network_mode: host
    # mount the directory containing the web app files to "/var/www/html"
    volumes:
    - "../:/var/www/html:ro"
    restart: unless-stopped
    # command: "/bin/bash"
