name: "file_browser"
services:
  filebrowser_container:
    image: "filebrowser/filebrowser"
    volumes:
    - "./data/root:/srv"
    - "./data/filebrowser.db:/database.db"
    user: "1000:1000"
    ports:
    - "80:80"
    restart: unless-stopped
