# unceremoniously stolen (and repaired) from https://github.com/pocketpairjp/palworld-dedicated-server-docker

name: "palworld"

networks:
  net:
    name: "palworld"
    external: false

services:

  setup:
    container_name: "palworld_setup"
    networks:
    - "net"
    # spawn the container from a Dockerfile
    build:
      context: "./"
      target: "setup_image"
    image: "palworld/setup"
    # mount the "./data" directory to write the config file into
    volumes:
    - "/srv/docker_data/palworld:/tmp/data"
    # have to mount the config yaml file to not have to rebuild the image when updating the settings
    - "./palworld_server_config.yml:/tmp/palworld_server_config.yml:ro"

  server:
    container_name: "palworld_server"
    networks:
    - "net"
    # spawn the container from a Dockerfile
    build:
      context: "./"
      target: "server_image"
    image: "palworld/server"
    # mount a local directory to save the server files
    volumes:
    - "/srv/docker_data/palworld:/pal/Package/Pal/Saved"
    # restart the container if it stops on its own
    restart: "unless-stopped"
    # expose the configured port over UDP
    ports:
    - "8211:8211/udp"
    # only start the server if the initialisation is successful
    depends_on:
      setup:
        condition: "service_completed_successfully"
    # debug
    # entrypoint: "bash"
