# sources:
# - https://www.youtube.com/watch?v=9nzHm3xGz2I
# - https://github.com/rustdesk/rustdesk-server/blob/master/docker-compose.yml

# in client, to connect to remote server:
# - add "ID server" and "Relay server": IP of docker host
# - add key: ./data/id_ed25519.pub content

# to wake up screen remotely :
#   loginctl unlock-session <session_id>
# the session id is the one with the line "Service=gdm-password" when running the command :
#   loginctl list-sessions --no-legend | while read id rest; do echo; loginctl show-session $id; done

name: rustdesk

networks:
  rustdesk-net:
    external: false

services:
  hbbs:
    container_name: hbbs
    ports:
    - 21115:21115
    - 21116:21116
    - 21116:21116/udp
    - 21118:21118
    image: rustdesk/rustdesk-server:latest
    command: hbbs -r arthurs-crib.ddns.net:21117
    volumes:
    - ./data:/root
    networks:
    - rustdesk-net
    depends_on:
    - hbbr
    restart: unless-stopped

  hbbr:
    container_name: hbbr
    ports:
    - 21117:21117
    - 21119:21119
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
    - ./data:/root
    networks:
    - rustdesk-net
    restart: unless-stopped
