name: "apache_php_server"

services:

  apache_php_container:
    container_name: "apache_php_container"
    # spawn from a Dockerfile
    build:
      context: "./"
      target: "apache_server_img"
    # mount the directory containing the web app files to "/var/www/html"
    volumes:
    - "D:\\code\\esaip_repo\\S3\\php\\9_immatriculation:/var/www/html:ro"
    # expose the HTTP port
    ports:
    - "80:80"
