name: ssh_server

services:

  ssh_server_container:

    # spawn from a Dockerfile
    build:
      context: ./
      target: ssh_server_image # specified in the Dockerfile with the "AS <target>" instruction

    # mount a persistent directory on /mnt
    volumes:
      - "./mnt:/mnt"

    # expose the ports the container communicates with (<host>:<container>)
    # here, only ssh
    ports:
      - "22:22"
