name: "ssh_server"

services:

  ssh_server_container:
    # spawn from a Dockerfile
    build:
      context: "./"
      target: "ssh_server_image" # specified in the Dockerfile with the "AS <target>" instruction
    # mount a persistent directory on /mnt
    volumes:
      - "./data:/mnt"
    # expose the ports the container communicates with (<host>:<container>)
    # here, only SSH
    ports:
      - "22:22"
    # command: "bash"
    # pull the last version of personal_dump before launching the server
    command: "bash -c 'cd /home/arthur/personal_dump/
      && git pull
      && cd /
      && /usr/sbin/sshd -D'"
