# multidomain certificate
# https://www.baeldung.com/linux/x-509-certificate-common-name-subject-alternative-names
# CN :
# - 100.124.238.99.nip.io
# SAN :
# - 100.124.238.99.nip.io
# - *.100.124.238.99.nip.io
# openssl command (https://stackoverflow.com/a/64344995) :
# openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./self.key -out ./self.crt -subj /C=FR/ST=Dev/L=Local/O=LocalDev/OU=Dev/CN=100.124.238.99.nip.io -addext "subjectAltName=DNS:100.124.238.99.nip.io,DNS:*.100.124.238.99.nip.io"

### WEB2MP3 ###

# redirect http:// to https://
server {
    # server_name web2mp3.100.124.238.99.nip.io;
    listen 80;
    return 301 https://$host$request_uri;
}

# we2mp3
server {
    server_name web2mp3.100.124.238.99.nip.io;

    http2 on;
    listen 443 ssl;

    # http3 on;
    # listen 443 quic reuseport;

    ssl_certificate /etc/nginx/certs/self.crt;
    ssl_certificate_key /etc/nginx/certs/self.key;
    # ssl_protocols TLSv1.2 TLSv1.3;
    # quic_retry on;
    # ssl_early_data on;

    location / {
        # proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        # for Reverb web sockets
        proxy_set_header Scheme $scheme;
        proxy_set_header SERVER_PORT $server_port;
        proxy_set_header REMOTE_ADDR $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_pass http://web2mp3_nginx;
    }
}

# filebrowser
server {
    server_name filebrowser.100.124.238.99.nip.io;

    http2 on;
    listen 443 ssl;

    ssl_certificate /etc/nginx/certs/self.crt;
    ssl_certificate_key /etc/nginx/certs/self.key;

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://filebrowser;
    }
}
